name: Docker Compose on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies API_jokes
        run: |
          pwd
          
          
      - name: runn docker 
        run: |
          docker build -t nginx-run .
          docker run -d -p 3001:3001 nginx-run 
